# 라이브러리 불러오기 및 데이터셋 path설정

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

path = 'dataset/'

## 데이터 불러오기 및 정렬

In [195]:
row_data = pd.read_csv('{}v7_final.csv'.format(path), encoding='euc-kr')#, index_col='Unnamed: 0')
row_data.head()

,회사명,거래소코드,회계년도,산업코드,소속코드,상장일,상장폐지일,감사의견코드,총자본증가율,유형자산증가율,...,PCR(Price cash-flow ratio)(최고),PCR(Price cash-flow ratio)(최저),PSR(Price sales ratio)(최고),PSR(Price sales ratio)(최저),기업가치(EV)(백만원),EBITDA(백만원),EBITDA/매출액(%),EBITDA/금융비용(배),EBITDA/평균발행주식수(백만원),EV/EBITDA(배)
0,(주)CMG제약,58820,2007/12,32102.0,5.0,2001/08/31,NaN,UQ,120.08,215.25,...,0.0,0.0,149.75,20.92,69545.33,-1288.45,-71.74,0.00,-104.44,0.00
1,(주)CMG제약,58820,2008/12,32102.0,5.0,2001/08/31,NaN,UQ,56.55,55.67,...,0.0,0.0,9.13,1.49,-454.50,-3419.79,-31.64,-4.56,-221.19,NaN
2,(주)CMG제약,58820,2009/12,32102.0,5.0,2001/08/31,NaN,UQ,-33.92,-8.50,...,0.0,0.0,8.40,1.72,26517.58,-7100.69,-69.98,-6.80,-443.98,NaN
3,(주)CMG제약,58820,2010/12,32102.0,5.0,2001/08/31,NaN,UQ,5.66,-11.92,...,0.0,0.0,3.22,1.04,31200.74,-5598.06,-49.32,-5.51,-243.34,NaN
4,(주)CMG제약,58820,2011/12,32102.0,5.0,2001/08/31,NaN,UQ,14.18,7.86,...,0.0,0.0,3.14,1.05,37758.74,2038.64,11.48,11.24,46.75,18.52

In [196]:
row_data = row_data[~row_data['산업코드'].isnull()]

In [197]:
row_data['소속코드'] = row_data['소속코드'].astype(int)
row_data['산업코드'] = row_data['산업코드'].astype(int)

In [198]:
row_data['소속코드'] = row_data['소속코드'].astype(str).str.zfill(2)
row_data['산업코드'] = row_data['산업코드'].astype(str).str.zfill(6)
row_data['거래소코드'] = row_data['거래소코드'].astype(str).str.zfill(6)

In [199]:
row_data['산업대분류'] = row_data['산업코드'].str[0:2]
# row_data

In [200]:
# 원데이터에서 에초에 모집단으로 선정한 산업대분류 코드 3, 10, 7을 추출하여 새로운 data를 만들어줍니다.
data = row_data[(row_data['산업대분류'] == '03') |
                (row_data['산업대분류'] == '10') | 
                (row_data['산업대분류'] == '07')]
# data.head()
data['회계년도_new']=data['회계년도'].str[0:4].astype(int)
data['상장일_new']=data['상장일'].str[0:4].astype(int)

/var/folders/1v/ctxpzb994v98h43xyk972tmc0000gn/T/ipykernel_6332/23027327.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['회계년도_new']=data['회계년도'].str[0:4].astype(int)
/var/folders/1v/ctxpzb994v98h43xyk972tmc0000gn/T/ipykernel_6332/23027327.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['상장일_new']=data['상장일'].str[0:4].astype(int)

In [201]:
data.loc[((data['감사의견코드'] == 'DS') | (data['감사의견코드'] == 'DU')) & (data['소속코드'].isin(['03','04','06'])), '부도여부'] = '1'

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [202]:
data.sort_values(by=['회사명','회계년도'], inplace=True)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [237]:
# data.loc[data['부도여부'] == '1']['회사명'].nunique() #.value_counts()
data.loc[data['부도여부'] == '1']['거래소코드'].nunique()

228

In [228]:
data['sum_nan'] =data[data['상장일_new'] == data['회계년도_new']].isnull().sum(1)

/var/folders/1v/ctxpzb994v98h43xyk972tmc0000gn/T/ipykernel_6332/933626273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sum_nan'] =data[data['상장일_new'] == data['회계년도_new']].isnull().sum(1)

In [235]:
data['sum_nan'] = data['sum_nan'].fillna(0)
data = data.loc[data['sum_nan'] <167]
data.drop(columns='sum_nan', inplace= True)
data

/var/folders/1v/ctxpzb994v98h43xyk972tmc0000gn/T/ipykernel_6332/3203968365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sum_nan'] = data['sum_nan'].fillna(0)
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,회사명,거래소코드,회계년도,산업코드,소속코드,상장일,상장폐지일,감사의견코드,총자본증가율,유형자산증가율,...,기업가치(EV)(백만원),EBITDA(백만원),EBITDA/매출액(%),EBITDA/금융비용(배),EBITDA/평균발행주식수(백만원),EV/EBITDA(배),산업대분류,회계년도_new,상장일_new,부도여부
0,(주)CMG제약,058820,2007/12,032102,05,2001/08/31,NaN,UQ,120.08,215.25,...,69545.33,-1288.45,-71.74,0.00,-104.44,0.00,03,2007,2001,NaN
1,(주)CMG제약,058820,2008/12,032102,05,2001/08/31,NaN,UQ,56.55,55.67,...,-454.50,-3419.79,-31.64,-4.56,-221.19,NaN,03,2008,2001,NaN
2,(주)CMG제약,058820,2009/12,032102,05,2001/08/31,NaN,UQ,-33.92,-8.50,...,26517.58,-7100.69,-69.98,-6.80,-443.98,NaN,03,2009,2001,NaN
3,(주)CMG제약,058820,2010/12,032102,05,2001/08/31,NaN,UQ,5.66,-11.92,...,31200.74,-5598.06,-49.32,-5.51,-243.34,NaN,03,2010,2001,NaN
4,(주)CMG제약,058820,2011/12,032102,05,2001/08/31,NaN,UQ,14.18,7.86,...,37758.74,2038.64,11.48,11.24,46.75,18.52,03,2011,2001,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25102,흥구석유(주),024060,2016/12,074607,05,1994/12/07,NaN,UQ,1.39,-5.61,...,55934.79,1348.52,0.94,10.71,89.90,41.48,07,2016,1994,NaN
25103,흥구석유(주),024060,2017/12,074607,05,1994/12/07,NaN,UQ,0.98,-0.56,...,46036.63,1147.56,0.74,9.02,76.50,40.12,07,2017,1994,NaN
25104,흥구석유(주),024060,2018/12,074607,05,1994/12/07,NaN,UQ,-5.89,-0.36,...,36557.57,1451.79,0.87,16.83,96.79,25.18,07,2018,1994,NaN
25105,흥구석유(주),024060,2019/12,074607,05,1994/12/07,NaN,UQ,11.24,-7.00,...,78081.78,1009.25,0.67,507.93,67.28,77.37,07,2019,1994,NaN
25106,흥구석유(주),024060,2020/12,074607,05,1994/12/07,NaN,UQ,0.07,-13.92,...,107308.51,16.31,0.01,0.00,1.09,6579.47,07,2020,1994,NaN

In [231]:
data

,회사명,거래소코드,회계년도,산업코드,소속코드,상장일,상장폐지일,감사의견코드,총자본증가율,유형자산증가율,...,EBITDA(백만원),EBITDA/매출액(%),EBITDA/금융비용(배),EBITDA/평균발행주식수(백만원),EV/EBITDA(배),산업대분류,회계년도_new,상장일_new,부도여부,sum_nan
0,(주)CMG제약,058820,2007/12,032102,05,2001/08/31,NaN,UQ,120.08,215.25,...,-1288.45,-71.74,0.00,-104.44,0.00,03,2007,2001,NaN,NaN
1,(주)CMG제약,058820,2008/12,032102,05,2001/08/31,NaN,UQ,56.55,55.67,...,-3419.79,-31.64,-4.56,-221.19,NaN,03,2008,2001,NaN,NaN
2,(주)CMG제약,058820,2009/12,032102,05,2001/08/31,NaN,UQ,-33.92,-8.50,...,-7100.69,-69.98,-6.80,-443.98,NaN,03,2009,2001,NaN,NaN
3,(주)CMG제약,058820,2010/12,032102,05,2001/08/31,NaN,UQ,5.66,-11.92,...,-5598.06,-49.32,-5.51,-243.34,NaN,03,2010,2001,NaN,NaN
4,(주)CMG제약,058820,2011/12,032102,05,2001/08/31,NaN,UQ,14.18,7.86,...,2038.64,11.48,11.24,46.75,18.52,03,2011,2001,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25102,흥구석유(주),024060,2016/12,074607,05,1994/12/07,NaN,UQ,1.39,-5.61,...,1348.52,0.94,10.71,89.90,41.48,07,2016,1994,NaN,NaN
25103,흥구석유(주),024060,2017/12,074607,05,1994/12/07,NaN,UQ,0.98,-0.56,...,1147.56,0.74,9.02,76.50,40.12,07,2017,1994,NaN,NaN
25104,흥구석유(주),024060,2018/12,074607,05,1994/12/07,NaN,UQ,-5.89,-0.36,...,1451.79,0.87,16.83,96.79,25.18,07,2018,1994,NaN,NaN
25105,흥구석유(주),024060,2019/12,074607,05,1994/12/07,NaN,UQ,11.24,-7.00,...,1009.25,0.67,507.93,67.28,77.37,07,2019,1994,NaN,NaN
25106,흥구석유(주),024060,2020/12,074607,05,1994/12/07,NaN,UQ,0.07,-13.92,...,16.31,0.01,0.00,1.09,6579.47,07,2020,1994,NaN,NaN

In [188]:
data['left_on'] = data['회계년도_new']-1

/var/folders/1v/ctxpzb994v98h43xyk972tmc0000gn/T/ipykernel_6332/2157095088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['left_on'] = data['회계년도_new']-1

In [190]:
left_df = data[['회사명', '거래소코드','부도여부', 'left_on']]
left_df

            회사명   거래소코드 부도여부  left_on
0      (주)CMG제약  058820  NaN     2006
1      (주)CMG제약  058820  NaN     2007
2      (주)CMG제약  058820  NaN     2008
3      (주)CMG제약  058820  NaN     2009
4      (주)CMG제약  058820  NaN     2010
...         ...     ...  ...      ...
25102   흥구석유(주)  024060  NaN     2015
25103   흥구석유(주)  024060  NaN     2016
25104   흥구석유(주)  024060  NaN     2017
25105   흥구석유(주)  024060  NaN     2018
25106   흥구석유(주)  024060  NaN     2019

[21183 rows x 4 columns]

In [192]:
merged_df = pd.merge(left_df, data, left_on=['회사명','left_on'], right_on = ['회사명','회계년도_new'], how='left')
merged_df

,회사명,거래소코드_x,부도여부_x,left_on_x,거래소코드_y,회계년도,산업코드,소속코드,상장일,상장폐지일,...,EBITDA(백만원),EBITDA/매출액(%),EBITDA/금융비용(배),EBITDA/평균발행주식수(백만원),EV/EBITDA(배),산업대분류,회계년도_new,상장일_new,부도여부_y,left_on_y
0,(주)CMG제약,058820,NaN,2006,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)CMG제약,058820,NaN,2007,058820,2007/12,032102,05,2001/08/31,NaN,...,-1288.45,-71.74,0.00,-104.44,0.00,03,2007.0,2001.0,NaN,2006.0
2,(주)CMG제약,058820,NaN,2008,058820,2008/12,032102,05,2001/08/31,NaN,...,-3419.79,-31.64,-4.56,-221.19,NaN,03,2008.0,2001.0,NaN,2007.0
3,(주)CMG제약,058820,NaN,2009,058820,2009/12,032102,05,2001/08/31,NaN,...,-7100.69,-69.98,-6.80,-443.98,NaN,03,2009.0,2001.0,NaN,2008.0
4,(주)CMG제약,058820,NaN,2010,058820,2010/12,032102,05,2001/08/31,NaN,...,-5598.06,-49.32,-5.51,-243.34,NaN,03,2010.0,2001.0,NaN,2009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21248,흥구석유(주),024060,NaN,2015,024060,2015/12,074607,05,1994/12/07,NaN,...,856.25,0.55,15.54,57.08,56.14,07,2015.0,1994.0,NaN,2014.0
21249,흥구석유(주),024060,NaN,2016,024060,2016/12,074607,05,1994/12/07,NaN,...,1348.52,0.94,10.71,89.90,41.48,07,2016.0,1994.0,NaN,2015.0
21250,흥구석유(주),024060,NaN,2017,024060,2017/12,074607,05,1994/12/07,NaN,...,1147.56,0.74,9.02,76.50,40.12,07,2017.0,1994.0,NaN,2016.0
21251,흥구석유(주),024060,NaN,2018,024060,2018/12,074607,05,1994/12/07,NaN,...,1451.79,0.87,16.83,96.79,25.18,07,2018.0,1994.0,NaN,2017.0
21252,흥구석유(주),024060,NaN,2019,024060,2019/12,074607,05,1994/12/07,NaN,...,1009.25,0.67,507.93,67.28,77.37,07,2019.0,1994.0,NaN,2018.0

In [187]:
sub = data.loc[data['회계년도_new'] == 2008]
# sub[fucking_nan].isna().sum()
sub

,회사명,거래소코드,회계년도,산업코드,소속코드,상장일,상장폐지일,감사의견코드,총자본증가율,유형자산증가율,...,기업가치(EV)(백만원),EBITDA(백만원),EBITDA/매출액(%),EBITDA/금융비용(배),EBITDA/평균발행주식수(백만원),EV/EBITDA(배),산업대분류,회계년도_new,상장일_new,부도여부
1,(주)CMG제약,058820,2008/12,032102,05,2001/08/31,NaN,UQ,56.55,55.67,...,-454.50,-3419.79,-31.64,-4.56,-221.19,NaN,03,2008,2001,NaN
15,(주)DB하이텍,000990,2008/12,032601,01,1975/12/12,NaN,UQ,3.76,1.41,...,1923832.20,173130.75,12.85,0.98,4636.57,11.11,03,2008,1975,NaN
29,(주)ES큐브,050120,2008/12,074604,05,2002/04/25,NaN,UQ,12.31,13.95,...,710.20,-2436.29,-18.76,-32.11,-120.24,NaN,07,2008,2002,NaN
43,(주)LG데이콤,015940,2008/12,106102,04,1993/01/30,2010/01/15,UQ,3.14,6.63,...,130429.68,348978.08,21.19,22.59,4190.06,0.37,10,2008,1993,NaN
44,(주)LG파워콤,045820,2008/12,106102,04,2008/11/27,2010/01/15,UQ,16.45,10.16,...,564579.81,369664.63,29.02,9.47,3044.23,1.53,10,2008,2008,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25001,환인제약(주),016580,2008/12,032102,01,1996/07/03,NaN,UQ,1.26,-2.03,...,-17695.83,17295.00,18.61,27408.88,1859.67,-1.02,03,2008,1996,NaN
25028,효성오앤비(주),097870,2008/06,032003,05,2008/04/08,NaN,UQ,147.42,-3.94,...,-2912.27,4492.57,19.63,29.33,1012.11,-0.65,03,2008,2008,NaN
25054,휴림로봇(주),090710,2008/12,032902,05,2006/12/05,NaN,UQ,21.45,-45.51,...,2160.30,1193.54,7.20,5.10,204.58,1.81,03,2008,2006,NaN
25086,휴켐스(주),069260,2008/12,032004,01,2002/10/07,NaN,UQ,24.10,18.01,...,14306.73,61662.98,14.83,41.44,2896.21,0.23,03,2008,2002,NaN
25094,흥구석유(주),024060,2008/12,074607,05,1994/12/07,NaN,UQ,-7.04,-0.55,...,5806.83,2513.66,1.74,9.59,167.58,2.31,07,2008,1994,NaN

In [83]:
# 재무비율 명칭을 정렬합니다.
financial_ratio = []
for i in data.columns[11:-1]:
    financial_ratio.append(i)
    print(i)

len(financial_ratio)

총자본증가율
유형자산증가율
유동자산증가율
영업이익증가율
경상이익증가율 (2007년 이전 발생)
순이익증가율
재고자산증가율
자기자본증가율
매출액증가율
종업원1인당 부가가치증가율
종업원수증가율
비유동자산증가율
종업원1인당 매출액증가율
종업원1인당 인건비증가율
매출액총이익률
매출액영업이익률
매출액경상이익률 (2007년 이전 발생)
매출액순이익률
총자본사업이익률
총자본영업이익률
총자본경상이익률 (2007년 이전 발생)
총자본순이익률
자기자본영업이익률
자기자본경상이익률 (2007년 이전 발생)
자기자본순이익률
자본금영업이익률
자본금경상이익률 (2007년 이전 발생)
자본금순이익률
조세 대 조세차감전순이익률
기업경상이익률 (2007년 이전 발생)
투자수익률 (2007년 이전 발생)
기업순이익률
경영자본영업이익률
경영자본순이익률
매출원가 대 매출액비율
영업비율
영업외손익률
금융비용부담률
외환이익 대 매출액비율
광고선전비 대 매출액비율
수지비율
인건비 대 총비용비율
조세공과 대 총비용비율
금융비용 대 총비용비율
감가상각비 대 총비용비율
감가상각률
누적감가상각률
이자부담률
지급이자율
차입금평균이자율
사내유보율
사내유보 대 자기자본비율
적립금비율(재정비율)
평균배당률
자기자본배당률
배당성향
1주당매출액(원)
EPS(Earning Per Share)(원)
1주당경상이익 (2007년 이전 발생)(원)
CPS(Cash flow Per Share)(원)
BPS(Book-value Per Share)(원)
유보율
R & D 투자효율
1주당영업이익(원)
유동자산구성비율
재고자산 대 유동자산비율
유동자산 대 비유동자산비율
당좌자산구성비율
비유동자산구성비율
자기자본구성비율
타인자본구성비율
자기자본배율
비유동비율
비유동장기적합률
유동비율
당좌비율
현금비율
원재료비율
매출채권비율
재고자산 대 순운전자본비율
매출채권 대 매입채무비율
매출채권 대 상
매입채무 대 재고자산비율
부채비율
유동부채비율
단기차입금 대 총차입금비율
비유동부채비율
비유동부채 대 순운전자본비율
순운전자본비율
차입금의존도
차입금비율
이자보상배율(이자비용)
이자보상배율(순금융비용)
유보액대비율
유보액 대 납입자본배율
유동자산집중도
비유동자산집중도
투자집중도
CASH FLOW 대 부채비율
CASH FLOW 대 차입금비율
CASH FLOW 대 총자본비율
CASH FLOW 대 매출액비율
영업이익대비이자보상배율
총자본회전률
경영자본회전률
자기자본회전률
자본금회전률
타인자본회전률
매입채무회전률
매입채무회전기간
유동자산회전률
당좌자산회전률
재고자산회전률
재고자산회전기간
상품
원
재공품회전률
매출채권회전률
매출채권회전기간
비유동자산회전률
유형자산회전율
순운전자본회전률
운전자본회전률
1회전기간
부가가치(백만원)
종업원1인당 부가가치(백만원)
종업원1인당 매출액(백만원)
종업원1인당 경상이익 (2007년 이전 발생)(백만원)
종업원1인당 순이익(백만원)
종업원1인당 인건비(백만원)
노동장비율
기계장비율
자본집약도
총자본투자효율
설비투자효율
기계투자효율
부가가치율
노동소득분배율
자본분배율
이윤분배율
부가가치(백만원).1
법인세비용차감전(계속사업)손익(백만원)
인건비(백만원)
금융비용(백만원)
임차료(백만원)
조세공과(백만원)
감가상각비(백만원)
종업원1인당 부가가치(백만원).1
총자본투자효율.1
기계투자효율.1
부가가치율.1
종업원수
PER(Price earnings ratio)(최고)
PER(Price earnings ratio)(최저)
PBR(Price book-value ratio)(최고)
PBR(Price book-value ratio)(최저)
PCR(Price cash-flow ratio)(최고)
PCR(Price cash-flow ratio)(최저)
PSR(Price sales ratio)(최고)
PSR(Price sales ratio)(최저)
기업가치(EV)(백만원)
EBITDA(백만원)
EBITDA/매출액(%)
EBITDA/금융비용(배)
EBITDA/평균발행주식수(백만원)
EV/EBITDA(배)

166

In [39]:
# 기존에 부도기업으로 분류한 dataset을 불러옵니다.
label = pd.read_csv('{}unique_firm.csv'.format(path), encoding='utf-8', index_col='Unnamed: 0')
label.head()

,회사명,거래소코드,회계년도,산업코드,업종코드,소속코드,상장일,상장폐지일,감사의견코드,감사의견,산업대분류,회계년도_new
0,(주)바로크가구,17120,2000.12.1,33201,1,4,1989.12.18,2001.7.10,DU,"경상손실 23,819백만원 발생, 총자산을 초과한 총부채액이 132,195백만원 발...",3,2000
1,쌍용자동차(주),3620,2000.12.1,33001,1,3,1975.5.21,NaN,DU,"영업손실 259,221백만원 총자산을 초과한 총부채액이 949,281백만원이 발생....",3,2000
2,(주)골드앤에스,35290,2000.12.1,105801,1,6,1999.12.7,NaN,DU,"경상손실 8,098백만원 이상, 유동자산을 초과하는 유동부채가 6,657백만원 이상...",10,2000
3,(주)대우,3810,2000.12.1,74607,1,4,1977.6.30,2001.5.23,DU,"총부채가 총자산보다 14,031,384백만원 초과,누적결손금이 14,917,023백...",7,2000
4,(주)태화쇼핑,15880,2000.12.1,74701,1,4,1994.11.5,2001.9.22,DU,"경상순손실 22,543백만원 상거래 정리채권 5,996백만원 이자 4,756백만원 미상환",7,2000

In [129]:


label[label['회계년도_new'] == 2008] #['회계년도_new'].value_counts()

,회사명,거래소코드,회계년도,산업코드,업종코드,소속코드,상장일,상장폐지일,감사의견코드,감사의견,산업대분류,회계년도_new
86,(주)지비에스,76170,2008.12.1,105901,1,4,2004.1.16,2009.4.22,DU,"2009년 2월 20일 파산을 선고하였으며, 회사의 주된 영업인 극장을 임대하여 이...",10,2008
87,(주)포넷,48270,2008.12.1,105801,1,4,2003.1.24,2009.5.4,DU,자본완전잠식 및 용역매출 관련 자산을 타 사에 양도함으로 인하여 사업을 중단하는 등...,10,2008
88,(주)피더블유제네틱스,65910,2008.12.1,106201,1,4,2003.1.10,2009.4.18,DU,"영업손실 5,830백만원, 당기순손실 33,608백만원, 유동자산을 초과하는 유동부...",10,2008
89,(주)야호커뮤니케이션,59720,2008.12.1,106301,1,4,2002.1.17,2009.5.27,DS,지분법적용투자주식에 대한 감사범위의 제한 때문에 회사가 제시한 재무제표에 대하여 회...,10,2008
90,(주)미디어코프,53890,2008.12.1,105801,1,4,2002.5.7,2009.4.11,DU,"추가우발부채의 파악을 할 수 없고, 관련 주석사항을 미제출하였으며 당기순순실이 93...",10,2008
91,(주)엑스씨이,81500,2008.12.1,106201,1,4,2006.7.21,2009.4.29,DU,"급격한 매출 감소 등으로 영업손실 및 당기순손실이 발생하고, 유동부채가 유동자산을 ...",10,2008
92,(주)디에스피이엔티,16040,2008.12.1,33003,1,4,1993.12.7,2009.4.11,DU,유동부채가 유동자산을 110억원만큼 초과하고 누적결손으로 인하여 총부채가 총자산을 ...,3,2008
93,(주)비에이치케이,3990,2008.12.1,74608,1,4,1976.12.22,2009.4.30,DS,"감사범위 제한 때문에 현금흐름표, 재무제표에 대한 주석을 제시받지 못하였으며, 일부...",7,2008
94,(주)도움,78610,2008.12.1,32604,1,4,2005.5.9,2009.4.11,DU,"영업손실은 93억원 당기순손실 546억원, 유동부채가 유동자산을 375억원 초과하며...",3,2008
95,(주)에프아이투어,47370,2008.12.1,32604,1,4,2001.5.29,2009.4.11,DU,"영업손실 346백만원, 당기순손실 19,598백만원 발생, 유동부채가 유동자산을 1...",3,2008
96,모빌링크텔레콤(주),41310,2008.12.1,32604,1,4,2000.5.9,2009.4.23,DU,"매출채권 등 일부의 실재성과 관련하여 충분한 감사증거를 확인할 수 없었고, 총자산을...",3,2008
97,(주)코스모스피엘씨,53170,2008.12.1,105802,1,4,2002.1.10,2009.4.30,DU,"수익모델 창출 지연, 중단사업 자산 매각 지연 등으로 영업손실 2,583백만원, 당...",10,2008
98,(주)아이디에이치,26230,2008.12.1,32902,1,4,1995.10.6,2009.4.29,DU,"유동부채가 유동자산을 825억원 및 총부채가 총자산을 732억만큼 초과하고, 200...",3,2008
99,우수씨엔에스(주),60550,2008.12.1,31401,1,4,2002.2.28,2009.4.11,DU,"영업손실 42억원, 당기순손실 751억원 및 유동부채가 유동자산을 565억원 초과,...",3,2008
100,(주)자강,36790,2008.12.1,32604,1,4,1999.12.16,2009.5.15,DU,"영업손실 6,681백만원 및 당기순손실 28,795백만원 발생하고, 유동부채가 유동...",3,2008
101,(주)쿨투,56020,2008.12.1,32701,1,4,2003.7.4,2009.4.29,DU,"영업손실 11,455백만원, 당기순손실 40,143백만원 발생, 유동부채가 유동자산...",3,2008
102,(주)쓰리소프트,36360,2008.12.1,32604,1,4,2001.1.18,2009.4.29,DU,"당기순손실 29,272백만원이 발생하고, 총부채가 총자산을 22,179백만원 초과함...",3,2008
103,유리이에스(주),7050,2008.12.1,32902,1,4,1975.12.27,2009.4.15,DU,"당기순손실 23,102백만원, 실재성 및 회수가능성을 확인할 수 없는 선급금 등 1...",3,2008
104,(주)포이보스,38810,2008.12.1,31802,1,4,2000.5.9,2009.4.11,DU,"제3자 채무에 대한 지급보증 19,368백만원과 각종 투자원리금 상환 지급보증 1...",3,2008
105,케이엠에이치(주),9690,2008.12.1,32803,1,4,1990.1.29,2009.5.13,DS,주식양수도계약과 관련하여 소명되지 아니한 어음에 대해 상환의무의 존재 여부 및 그 ...,3,2008
106,(주)나노하이텍,71360,2008.12.1,32602,1,4,2003.10.24,2009.4.29,DU,"실재성 및 회수가능성을 확인할 수 없는 선급금 등 23,970백만원이 있으며, 총자...",3,2008
107,케이엔에스홀딩스(주),36760,2008.12.1,32602,1,4,1999.12.10,2009.4.23,DS,"자본변동표, 현금흐름표, 주석 미제시, 여러자산, 유동 및 비유동부채, 자본, 매...",3,2008
108,(주)기린,6070,2008.12.1,31007,1,4,1989.6.20,2009.5.13,DU,"유동자산을 초과하는 유동부채액 44,188백만원, 미처리결손금 24,522백만원, ...",3,2008
109,케이이엔지(주),77960,2008.12.1,32902,1,4,2004.10.29,2009.4.29,DU,"당기순손실 30,567백만원 발생, 유동자산을 초과하는 유동부채액 15,766백만원...",3,2008
110,(주)블루스톤디앤아이,33720,2008.12.1,105802,1,4,2000.6.27,2009.5.15,DU,회사가 600억원으로 계상하고 있는 SMI현대의 지분법적용주식의 가치에 대한 합리적...,10,2008
111,(주)위너스인프라인,5760,2008.10.1,74604,1,4,1976.4.1,2009.2.19,DU,"채무 불이행으로 대부분의 자산이 압류 또는 가압류, 자료 미제시로 계정의 적정성에 ...",7,2008

# 해야할 일
1. train, validation, test 3가지로 기간을 분리해야 합니다.
2. 부도기업 리스트를 활용하여 data를 분류하는 작업을 수행해야 합니다.
3. data를 분류하게 된다면 모집단을 2개로 나눈 후에 T-test를 시행합니다. (financial_ratio를 활용하여 진행)
   1. 하지만, t-test에 대한 가정 (모집단의 정규분포성 등)이 충족되는지 확인해야 합니다.

In [126]:
year_list = list(filter(lambda x: x, range(2000,2021,1)))